services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: coworking-backend
    image: coworking-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Coworking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      #MINIO_URL: http://localhost:9000 # это для локалки
      MINIO_URL: http://minio:9000 # это для контейнеров
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - db
      - minio

  frontend:
    build:
      context: ../../frontend/Coworking
      dockerfile: Dockerfile
    container_name: coworking-frontend
    image: coworking-frontend
    ports:
      - "4200:80"

  db:
    image: postgres:latest
    container_name: coworking-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Coworking
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: coworking-minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    volumes:
      - minio-data:/data

  nginx:
    image: nginx:stable-alpine
    container_name: coworking-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - C:\nginx\nginx-1.26.3\conf\nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  db-data:
  minio-data: